import * as lodash from './lodash.custom';
import * as errors from './errors';
export { lodash, errors };
export { assert, asrt } from './assert';
export { forEach } from './forEach';
export { indent } from './indent';
export { map } from './map';
export { promiseMap } from './promiseMap';
export { promiseReduce } from './promiseReduce';
export { reduce } from './reduce';
export { stringMatch } from './stringMatch';
export { setIf } from './setIf';
